etsy_app/etsy/urls.py
from django.conf.urls import patterns, url

from etsy_app.etsy import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'listings/(?P<category_id>\d+)/$', views.listings, name='listings'),
    url(r'listing/(?P<list_id>\d+)$', views.listing, name='listing'),
    url(r'listing/(?P<list_id>\d+)/keywords/$', views.listing_keywords, name='listing_keywords'),
    url(r'listing/(?P<list_id>\d+)/similar/$', views.listing_similar, name='listing_similar'),
    url(r'listing/(?P<list_id>\d+)/tags/$', views.recommend_tags, name='recommend_tags'),
    url(r'listing/(?P<list_id>\d+)/tags_title/$', views.recommend_tags_title, name='recommend_tags_title'),
    url(r'listing/(?P<list_id>\d+)/tags_category/$', views.recommend_tags_category, name='recommend_tags_categroy'),
    url(r'listing/(?P<list_id>\d+)/topics/$', views.listing_topics, name='listing_topics'),
    url(r'listings/test/$', views.test_listings, name='test_listings'),
)

etsy_app/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'etsy_app.views.home', name='home'),
    url(r'^etsy/', include('etsy_app.etsy.urls', namespace="etsy")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

etsy_app/etsy/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Style(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Material(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Listing(models.Model):
    RECIPIENT = (
            ('MEN', "men"), ('WOMEN', "women"), ('UNISEX_ADULT', "unisex_adult"), 
            ('TEEN_BOYS', "teen_boys"), ('TEEN_GIRLS', "teen_girls"), 
            ('TEENS', "teens"), ('GIRLS', "girls"), ('CHILDREN', "children"), 
            ('BABY_BOYS', "baby_boys"), ('BABY_GIRLS', "baby_girls"), ('BABIES', "babies"), 
            ('BIRDS', "birds"), ('CATS', "cats"), ('DOGS', "dogs"), 
            ('PETS', "pets"), ('NOT_SPECIFIED', "not_specified")
        )

    OCCASION = (
            ('ANNIVERSARY', "anniversary"), ('BAPTISM', "baptism"), ('BAR_OR_BAT_MITZVAH', "bar_or_bat_mitzvah"), 
            ('BIRTHDAY', "birthday"), ('CANDA_DAY', "canada_day"), ('CHINESE_NEW_YEAR', "chinese_new_year"), 
            ('CINCO_DE_MAYO', "cinco_de_mayo"), ('CONFIRMATION', "confirmation"), ('CHRISTMAS', "christmas"), 
            ('DAY_OF_THE_DEAD', "day_of_the_dead"), ('EASTER', "easter"), ('EID', "eid"), ('ENGAGEMENT', "engagement"), 
            ('FATHERS_DAY', "fathers_day"), ('GET_WELL', "get_well"), ('GRADUATION', "graduation"), 
            ('HALOWEEN', "halloween"), ('HANUKKAH', "hanukkah"), ('HOUSEWARMING', "housewarming"), ('KWANZAA', "kwanzaa"), 
            ('PROM', "prom"), ('JULY_4TH', "july_4th"), ('MOTHERS_DAY', "mothers_day"), ('NEW_BABY',"new_baby"), 
            ('NEW_YEARS', "new_years"), ('QUINCEANERA', "quinceanera"), ('RETIREMENT', "retirement"), 
            ('ST_PATRICKS_DAY', "st_patricks_day"), ('SWEET_16', "sweet_16"), ('SYMPATHY', "sympathy"), 
            ('THANKSGIVING', "thanksgiving"), ('VALENTINES', "valentines"), ('WEDDING', "wedding")
        )

    WHO_MADE = (
            ('I_DID', "i_did"), 
            ('COLLECTIVE', "collective"), 
            ('SOMEONE_ELSE', "someone_else")
        )

    class Meta:
        ordering = ['-views']

    title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    width = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    height = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    weight = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    length = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    views = models.BigIntegerField(null=True)
    listing_id = models.BigIntegerField(unique=True)
    favorers = models.BigIntegerField(null=True)
    quantity = models.IntegerField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=3, null=False)
    styles = models.ManyToManyField(Style, verbose_name="list of styles")
    tags = models.ManyToManyField(Tag, verbose_name="list of tags")
    materials = models.ManyToManyField(Material, verbose_name="list of materials")
    recipient = models.CharField(max_length=20, choices=RECIPIENT, null=True)
    occasion = models.CharField(max_length=20, choices=OCCASION, null=True)
    made_by = models.CharField(max_length=20, choices=WHO_MADE, null=True)
    has_variations = models.BooleanField(default=False)
    is_customizable = models.BooleanField(default=True)
    category = models.ForeignKey(Category, null=True)
    document_index = models.IntegerField(default=-1)
    corpus_name = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.title

etsy_app/etsy/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.db.models import Count

from etsy_app.etsy.models import *
from etsy_app.extract import *



def index(request):
    categories = Category.objects.annotate(listings_count=Count('listing')).filter(listings_count__gte=100).order_by('-listings_count')
    template = loader.get_template('etsy/index.html')
    context = RequestContext(request, {
        'categories': categories,
    })

    return HttpResponse(template.render(context))


def listings(request, category_id):
    category = Category.objects.get(id=category_id)
    listings = Listing.objects.filter(category__name=category.name)
    template = loader.get_template('etsy/listings.html')
    context = RequestContext(request, {
        'category': category,
        'listings': listings,
    })
    
    return HttpResponse(template.render(context))


def test_listings(request):
    categories = Category.objects.annotate(listings_count=Count('listing')).filter(listings_count__gte=100).order_by('-listings_count')
    listings = []

    for category in categories:
        listings.extend(Listing.objects.filter(category__name=category.name, document_index=-1))
        
    template = loader.get_template('etsy/listings.html')
    context = RequestContext(request, {
        'listings': listings,
        'test_set': True
    })
    
    return HttpResponse(template.render(context))


def listing(request, list_id):
    listing = Listing.objects.get(id=list_id)
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
    })
    
    return HttpResponse(template.render(context))


def listing_keywords(request, list_id):
    listing = Listing.objects.get(id=list_id)
    keywords = find_keywords(listing)
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'keywords': keywords
    })
    
    return HttpResponse(template.render(context))


def recommend_tags(request, list_id):
    listing = Listing.objects.get(id=list_id)
    tags = find_tags_from_similar(listing)
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'recommended_tags': tags
    })

    return HttpResponse(template.render(context))


def recommend_tags_title(request, list_id):
    listing = Listing.objects.get(id=list_id)
    tags = find_tags(listing, listing.title)
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'recommended_tags': tags
    })

    return HttpResponse(template.render(context))


def recommend_tags_category(request, list_id):
    listing = Listing.objects.get(id=list_id)
    tags = find_tags(listing, listing.category.name, 10)
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'recommended_tags': tags
    })

    return HttpResponse(template.render(context))


def listing_similar(request, list_id):
    listing = Listing.objects.get(id=list_id)
    if listing.document_index == -1:
        similar = find_similar(listing, 5)
    else:
        similar = find_similar_by_index(listing, 6)

    similar_items = [Listing.objects.get(document_index=index) for (index, metric) in similar 
                        if index != listing.document_index]
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'similar': similar_items
    })
    
    return HttpResponse(template.render(context))


def listing_topics(request, list_id):
    listing = Listing.objects.get(id=list_id)
    topics = find_latent_topics(listing)

    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'topics': topics
    })
    
    return HttpResponse(template.render(context))


def classify_keywords(request, list_id):
    #TODO better classifier
    listing = Listing.objects.get(id=list_id)
    keywords = ' '.join([word for word, metric in find_keywords(listing, 20)])
    category = suggest_category(keywords)
    template = loader.get_template('etsy/listing.html')
    context = RequestContext(request, {
        'listing': listing,
        'suggested_category': None
    })
    
    return HttpResponse(template.render(context))

templates/etsy/index.html
{% if categories %}
    <ul>
    {% for cat in categories %}
        <li><a href="{% url 'etsy:listings' cat.id %}">{{ cat.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No categories are available.</p>
{% endif %}

templates/etsy/listing.html
<h2> {{listing.title}} </h2>

<h3> Description </h3>
<p> {{listing.description}} </p>
{% if listing.styles.all %}
    <h3> Styles </h3>
    {% for s in listing.styles.all %}
        <li>{{ s.name }}</li>
    {% endfor %}
{% endif %}

{% if listing.materials.all %}
    <h3> Materials </h3>
    {% for m in listing.materials.all %}
        <li>{{ m.name }}</li>
    {% endfor %}
{% endif %}

{% if listing.tags.all %}
    <h3> Tags </h3>
    {% for t in listing.tags.all %}
        <li>{{ t.name }}</li>
    {% endfor %}
{% endif %}
<br>

<h3> Category </h3>
<p> {{listing.category}}</p>
{% if keywords %}
    <h3 style="color:red"> Suggested keywords </h3>
    {% for word, metric in keywords %}
        <li style="color:red">{{ word }}</li>
    {% endfor %}
{% else %}
<form action="{% url 'etsy:listing_keywords' listing.id %}" method="GET">
  <input type="submit" value="Suggest keywords">
</form>
{% endif %}

{% if similar %}
<h3 style="color:red"> Similar items </h3>
    {% for s in similar %}
        <li><a href="{% url 'etsy:listing' s.id %}" style="color:red">{{ s.title }}</a></li>
    {% endfor %}
{% endif %}

{%if recommended_tags %}
<h3 style="color:red"> Recommended tags </h3>
    {% for t in recommended_tags %}
        <li style="color:red">{{ t }}</li>
    {% endfor %}
{% endif %}

{% if topics %}
<h3 style="color:red"> Topic Terms </h3>
    {% for tt in topics %}
        <li style="color:red">{{ tt }}</li>
    {% endfor %}
{% endif %}

templates/etsy/listings.html
{% if category %}
    <h2> Items for category {{category.name}} </h2>
{% else %}
    <h2> Items used for tesing </h2>
{% endif %}

{% if test_set %}
    {% regroup listings by category as categories_list %}
    {% for category in categories_list %}
        <h3>{{ category.grouper }}</h3>
        <ul>
            {% for item in category.list %}
              <li><a href="{% url 'etsy:listing' item.id %}">{{ item.title }}</a></li>
            {% endfor %}
        </ul>
    {% endfor %}

{% else %}
    {% if listings %}
        <ul>
        {% for list in listings %}
            <li><a href="{% url 'etsy:listing' list.id %}">{{ list.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No items currently available for category {{category.name}}.</p>
    {% endif %}
{% endif %}